steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-http', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/go-http']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/nginxlamp', 'lamp=gcr.io/$PROJECT_ID/go-http']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=go-http'
images:
- 'gcr.io/$PROJECT_ID/go-http'
